import { launch, sleep } from './test_cdp.mjs';
const BASE = process.env.BYEOT_URL || 'http://localhost:8963';
const page = await launch({ width: 390, height: 844, dpr: 2, mobile: false });
const errs=[]; page.on(m=>{ if(m.method==='Runtime.exceptionThrown') errs.push((m.params.exceptionDetails.exception||{}).description||''); });
await page.goto(`${BASE}/game.html`); await page.eval(`localStorage.clear()`,false);
await page.goto(`${BASE}/game.html`);
await page.waitFor('window.__byeotBooted === true', 180000, 300); await sleep(6000);
const clear=async()=>{for(let i=0;i<30;i++){const b=await page.eval(`(()=>{const s=document.getElementById('stage'),g=document.getElementById('guide');return !!(s&&s.classList.contains('talking'))||!!(g&&g.classList.contains('on'));})()`); if(!b)return;
  await page.eval(`(()=>{const g=document.getElementById('guideClose'); if(g&&g.offsetParent){g.click();return;} const b=document.getElementById('dlgBox'); if(b)b.click();})()`,false); await sleep(250);}};
await clear();
const waitAct=async(ms=15000)=>{const t0=Date.now();const a=()=>page.eval(`(()=>{try{return !!window.__byeotWalkSfx().acting}catch{return false}})()`);
  for(let i=0;i<6;i++){if(await a())break;await sleep(120);} while(Date.now()-t0<ms){if(!(await a())){await sleep(250);return}await sleep(250);}};
const rowAct=async(act)=>{for(let k=0;k<8;k++){const hit=await page.eval(`(()=>{const b=[...document.querySelectorAll('#siruList button[data-act="${act}"]')].find(x=>!x.disabled); if(!b)return false; b.click(); return true;})()`); if(!hit)break; await waitAct(); await sleep(350); await clear();}};
await page.eval(`(()=>{const rv=window.__rv,c=document.getElementById('roomCanvas').getBoundingClientRect();
  const sp=rv.screenPosOf('banjiha-dresser:1');
  window.__drag.begin('beansprout',document.getElementById('cropThumb').src,{clientX:c.left+c.width*0.9,clientY:c.top+40});
  window.__drag.move({clientX:c.left+sp.x,clientY:c.top+sp.y});window.__drag.end();})()`,false);
await sleep(1200);
await page.eval(`(()=>{const S=window.__S(); S.shop.stock.bean_seed=9;})()`,false);
await page.eval(`(()=>{const b=document.getElementById('placeOk'); if(b&&b.offsetParent)b.click();})()`,false);
await sleep(900); await clear();
await page.eval(`window.__byeotSheet.open('plants')`,false); await sleep(500);
for(let i=0;i<60;i++){ if(await page.eval(`window.__S().pots.length>0`))break;
  await page.eval(`(()=>{const S=window.__S(); if(S.stamina)S.stamina.usedToday=0;})()`,false);
  await rowAct('plant'); await rowAct('water'); await rowAct('harvest'); await rowAct('sow');
  await page.eval(`(()=>{try{document.getElementById('next').click()}catch{}})()`,false); await sleep(900); await clear(); }
await page.eval(`window.__byeotSheet.open('plants')`,false); await sleep(900);
console.log('전 자리:', await page.eval(`(()=>{const S=window.__S(); return JSON.stringify(S.pots.map(p=>p.slotId));})()`));
await page.eval(`(()=>{const b=document.querySelector('[data-plantwhere]'); if(b)b.click();})()`,false);
await sleep(900);
console.log('자리 목록:', await page.eval(`(()=>{const p=document.getElementById('slotPanel');
  const rows=[...document.querySelectorAll('#slotList [data-slot]')].map(b=>({slot:b.dataset.slot,
    글:(b.textContent||'').replace(/\s+/g,' ').trim().slice(0,26), 잠김:b.disabled}));
  return JSON.stringify({열림:!!(p&&p.classList.contains('on')), 줄수:rows.length, 앞셋:rows.slice(0,3)});})()`));
await page.shot('docs/handoff/img/guidewalk/slotpick.png');
await page.eval(`(()=>{const b=[...document.querySelectorAll('#slotList [data-slot]')].find(x=>/sill/.test(x.dataset.slot)&&!x.disabled); if(b)b.click();})()`,false);
await sleep(1500); await clear();
console.log('누른 뒤:', await page.eval(`(()=>{const S=window.__S();
  return JSON.stringify({자리:S.pots.map(p=>p.slotId), 창닫힘:!document.getElementById('slotPanel').classList.contains('on')});})()`));
console.log('예외', errs.length, errs.slice(0,2).join(' | '));
await page.close();
