import { launch, sleep } from './test_cdp.mjs';
const BASE = process.env.BYEOT_URL || 'http://localhost:8963';
const page = await launch({ width: 390, height: 844, dpr: 2, mobile: false });
const urls=[]; page.on((m,p)=>{ if(m==='Network.requestWillBeSent' && /\.glb/i.test(p.request?.url||'')) urls.push(p.request.url.split('/assets/')[1]||p.request.url); });
await page.goto(`${BASE}/game.html`); await page.eval(`localStorage.clear()`,false);
await page.goto(`${BASE}/game.html`);
await page.waitFor('window.__byeotBooted === true', 180000, 300); await sleep(6000);
const clear=async()=>{for(let i=0;i<30;i++){const b=await page.eval(`(()=>{const s=document.getElementById('stage'),g=document.getElementById('guide');return !!(s&&s.classList.contains('talking'))||!!(g&&g.classList.contains('on'));})()`); if(!b)return;
  await page.eval(`(()=>{const g=document.getElementById('guideClose'); if(g&&g.offsetParent){g.click();return;} const b=document.getElementById('dlgBox'); if(b)b.click();})()`,false); await sleep(250);}};
await clear();
await page.eval(`(()=>{const S=window.__S(); S.shop.stock.monstera_seed=1; S.shop.stock.pot_concrete_square=1;
  if(S.firstPlay&&S.firstPlay.monstera)S.firstPlay.monstera.arrived=true; if(S.stamina)S.stamina.usedToday=0;
  window.__redraw&&window.__redraw();})()`,false);
await sleep(500);
urls.length=0;
await page.eval(`window.__placePot('monsteraSeed:pot_concrete_square')`,false);
await sleep(2500);
console.log('놓은 뒤 부른 GLB:', JSON.stringify(urls.filter(u=>/pot/i.test(u))));
console.log('빈화분 상태:', await page.eval(`(()=>{const S=window.__S(); return JSON.stringify((S.emptyPots||[]).map(e=>({id:e.id,itemId:e.itemId,potAsset:e.potAsset,potD:e.potD})));})()`));
await page.close();
