import { launch, sleep } from './test_cdp.mjs';
const BASE = process.env.BYEOT_URL || 'http://localhost:8963';
const page = await launch({ width: 390, height: 844, dpr: 2, mobile: false });
const urls=[]; const errs=[];
page.on((m,p)=>{ if(m==='Network.requestWillBeSent' && /\.glb/i.test(p.request?.url||'')) urls.push((p.request.url.split('/assets/')[1]||'').split('?')[0]);
  if(m==='Runtime.exceptionThrown') errs.push((p.exceptionDetails.exception||{}).description||''); });
await page.goto(`${BASE}/game.html`); await page.eval(`localStorage.clear()`,false);
await page.goto(`${BASE}/game.html`);
await page.waitFor('window.__byeotBooted === true', 180000, 300); await sleep(6000);
const clear=async()=>{for(let i=0;i<30;i++){const b=await page.eval(`(()=>{const s=document.getElementById('stage'),g=document.getElementById('guide');return !!(s&&s.classList.contains('talking'))||!!(g&&g.classList.contains('on'));})()`); if(!b)return;
  await page.eval(`(()=>{const g=document.getElementById('guideClose'); if(g&&g.offsetParent){g.click();return;} const b=document.getElementById('dlgBox'); if(b)b.click();})()`,false); await sleep(250);}};
await clear();
await page.eval(`(()=>{const S=window.__S();
  if(S.firstPlay&&S.firstPlay.monstera)S.firstPlay.monstera.arrived=true;
  S.shop.stock.pot_concrete_square=1; S.shop.stock.monstera_seed=2;
  if(S.stamina)S.stamina.usedToday=0; window.__redraw&&window.__redraw();})()`,false);
await sleep(600);
await page.eval(`window.__placePot('monsteraSeed:pot_concrete_square')`,false);
await sleep(1800); await clear();
urls.length=0;
await page.eval(`window.__byeotSheet.open('plants')`,false); await sleep(700);
await page.eval(`(()=>{const b=[...document.querySelectorAll('#emptyPotList [data-sow]')][0]; if(b)b.click();})()`,false);
await sleep(1300);
await page.eval(`(()=>{ for(const b of document.querySelectorAll('button')){
  if(/몬스테라/.test(b.textContent||'') && b.offsetParent && !b.disabled){b.click(); return;} } })()`,false);
await sleep(3000); await clear();
console.log('심은 뒤 부른 GLB:', JSON.stringify([...new Set(urls)].filter(u=>/pot/i.test(u))));
console.log('그루:', await page.eval(`(()=>{const S=window.__S();
  return JSON.stringify(S.pots.map(p=>({id:p.id, asset:p.potAsset})));})()`));
console.log('방 화분 조각:', await page.eval(`(()=>{ try {
  const rv=window.__rv; const rows=[];
  for (const r of rv.plants()) rows.push({key:r.key, kind:r.kind, potD:r.potD, potAsset:r.potAsset});
  return JSON.stringify(rows);
} catch(e){ return 'ERR '+e.message; } })()`));
console.log('예외', errs.length, errs.slice(0,2).join(' | '));
await page.close();
